# Generated by Django 3.0 on 2022-11-13 01:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='NameOfCard')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Cards', verbose_name='CardImage')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='CollectionName')),
                ('number_of_cards', models.IntegerField(verbose_name='NumberOfCards')),
                ('bonus_first_stage', models.IntegerField(verbose_name='BonusFirstStage')),
                ('bonus_second_stage', models.IntegerField(verbose_name='BonusSecondStage')),
                ('bonus_third_stage', models.IntegerField(verbose_name='BonusThirdStage')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Collections', verbose_name='CollectionImage')),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=models.SET('Deleted'), to='core.Card')),
                ('user', models.ForeignKey(on_delete=models.SET('Deleted'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardOwners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_acquired', models.DateTimeField(auto_now_add=True, verbose_name='DateTime')),
                ('card', models.ForeignKey(on_delete=models.SET('Deleted'), to='core.Card')),
                ('user', models.ForeignKey(on_delete=models.SET('Deleted'), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='collection_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Collection'),
        ),
    ]
